# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- vegeta-ns-1.yaml
- vegeta-ns-2.yaml
- vegeta-ns-3.yaml
- vegeta-ns-4.yaml
- vegeta-ns-5.yaml
- vegeta-ns-6.yaml
- vegeta-ns-7.yaml
- vegeta-ns-8.yaml
- vegeta-ns-9.yaml
- vegeta-ns-10.yaml
- vegeta-ns-11.yaml
- vegeta-ns-12.yaml
- vegeta-ns-13.yaml
- vegeta-ns-14.yaml
- vegeta-ns-15.yaml
- vegeta-ns-16.yaml
- vegeta-ns-17.yaml
- vegeta-ns-18.yaml
- vegeta-ns-19.yaml
- vegeta-ns-20.yaml
- vegeta-ns-21.yaml
- vegeta-ns-22.yaml
- vegeta-ns-23.yaml
- vegeta-ns-24.yaml
- vegeta-ns-25.yaml
- vegeta-ns-26.yaml
- vegeta-ns-27.yaml
- vegeta-ns-28.yaml
- vegeta-ns-29.yaml
- vegeta-ns-31.yaml
- vegeta-ns-32.yaml
- vegeta-ns-33.yaml
- vegeta-ns-34.yaml
- vegeta-ns-35.yaml
- vegeta-ns-36.yaml
- vegeta-ns-37.yaml
- vegeta-ns-38.yaml
- vegeta-ns-39.yaml
- vegeta-ns-40.yaml
- vegeta-ns-41.yaml
- vegeta-ns-42.yaml
- vegeta-ns-43.yaml
- vegeta-ns-44.yaml
- vegeta-ns-45.yaml
- vegeta-ns-46.yaml
- vegeta-ns-47.yaml
- vegeta-ns-48.yaml
- vegeta-ns-49.yaml
- vegeta-ns-50.yaml