# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- ../base

transformers:
- label-transformer.yaml
- suffix-transformer.yaml

# hostname patch
patchesJSON6902:
- target:
    group: networking.gloo.solo.io
    version: v2
    kind: RouteTable
    name: petstore-main
  patch: |-
    - op: replace
      path: /spec/hosts/0
      value: petstore.int.glooplatform.com

# portal metadata patch      
- target:
    group: networking.gloo.solo.io
    version: v2
    kind: RouteTable
    name: v1-petstore-rt
  patch: |-
    - op: replace
      path: /spec/portalMetadata/apiVersion
      value: v1
    - op: replace
      path: /spec/http/0/forwardTo/destinations/0/ref/namespace
      value: petstore
    - op: replace
      path: /spec/http/1/forwardTo/destinations/0/ref/namespace
      value: petstore
    - op: replace
      path: /spec/http/2/forwardTo/destinations/0/ref/namespace
      value: petstore

namespace: petstore