# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- vegeta-ns-1.yaml
- vegeta-ns-2.yaml
- vegeta-ns-3.yaml
- vegeta-ns-4.yaml
- vegeta-ns-5.yaml
- vegeta-ns-6.yaml
- vegeta-ns-7.yaml
- vegeta-ns-8.yaml
- vegeta-ns-9.yaml
- vegeta-ns-10.yaml
- vegeta-ns-11.yaml
- vegeta-ns-12.yaml
- vegeta-ns-13.yaml
- vegeta-ns-14.yaml
- vegeta-ns-15.yaml