apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: backstage
  namespace: backstage
spec:
  exportTo:
  - workspaces:
    - name: ops-team
  importFrom:
  - workspaces:
    - name: ops-team
  options:
    federation:                     # enable service federation of the web-ui namespace
      enabled: false
      serviceSelector:
      - namespace: backstage
    serviceIsolation:               # enable service isolation and Istio Sidecar resource
      enabled: true
      trimProxyConfig: true