apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollouts-demo-ns.yaml
- rollouts-demo.yaml
- rollouts-demo-rt-443.yaml
- rollouts-demo-workspace.yaml
- rollouts-demo-workspacesettings.yaml
- rollouts-ui

