# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- petstore-rt.yaml
#- petstore-rt-delegate.yaml
- petstore-workspace.yaml
- petstore-workspacesettings.yaml

