apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: betterchatgpt-okta
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://chat.gwapi.glooplatform.com
        callbackPath: /callback
        clientId: 0oa6qvzybcVCK6PcS5d7
        clientSecretRef:
          name: okta-client-secret
          namespace: gloo-system
        issuerUrl: https://dev-22653158.okta.com/oauth2/default
        scopes:
        - email
        headers:
          idTokenHeader: "x-token"