# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- gloo-enterprise.yaml
- gloo-system-ns.yaml
- postgres-db.yaml
- portal-database-config.yaml
