# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- bookinfo-extauth-policy.yaml
- bookinfo-oauth-rt-443.yaml
- bookinfo-ratelimit-transformationfilter.yaml
- bookinfo-ratelimitclientconfig.yaml
- bookinfo-ratelimitpolicy.yaml
- bookinfo-ratelimitserverconfig.yaml
- bookinfo-ratelimitserversettings.yaml
- bookinfo-wafpolicy-log4shell.yaml
- bookinfo-workspace.yaml
- bookinfo-workspacesettings.yaml
- ui-smoke-test.yaml

